spring:
    application:
        name: 'url-shortener'
    datasource:
        url: jdbc:postgresql://localhost:5432/urlshortener
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 5
            minimum-idle: 1
            initialization-fail-timeout: -1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        show-sql: true
    flyway:
        enabled: true
        locations: classpath:db/migration
server:
    port: 8082
        